default_agent: agent
agents:
  agent:
    name: agent
    language: python
    node_version: '20'
    entrypoint: C:/Users/silvjimm/KiroProject/HIA-AgentCore/agent/agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\silvjimm\KiroProject\HIA-AgentCore\agent
    aws:
      execution_role: arn:aws:iam::085794773476:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-d4f0bc5a29
      execution_role_auto_create: false
      account: 085794773476
      region: us-east-1
      ecr_repository: 085794773476.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: agent_mem-6JX6NZDv36
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:085794773476:memory/agent_mem-6JX6NZDv36
      memory_name: agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
